/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AddPetRequest,
    AddPetRequestFromJSON,
    AddPetRequestToJSON,
} from '../models/AddPetRequest';
import {
    type PetDto,
    PetDtoFromJSON,
    PetDtoToJSON,
} from '../models/PetDto';
import {
    type UpdatePetRequest,
    UpdatePetRequestFromJSON,
    UpdatePetRequestToJSON,
} from '../models/UpdatePetRequest';

export interface PetFindByStatusGetRequest {
    status?: string;
}

export interface PetFindByTagsGetRequest {
    tags?: Array<string>;
}

export interface PetPetIdDeleteRequest {
    petId: string;
}

export interface PetPetIdGetRequest {
    petId: string;
}

export interface PetPostRequest {
    addPetRequest?: AddPetRequest;
}

export interface PetPutRequest {
    updatePetRequest?: UpdatePetRequest;
}

/**
 * 
 */
export class PetApi extends runtime.BaseAPI {

    /**
     * Creates request options for petFindByStatusGet without sending the request
     */
    async petFindByStatusGetRequestOpts(requestParameters: PetFindByStatusGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pet/findByStatus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async petFindByStatusGetRaw(requestParameters: PetFindByStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PetDto>>> {
        const requestOptions = await this.petFindByStatusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PetDtoFromJSON));
    }

    /**
     */
    async petFindByStatusGet(requestParameters: PetFindByStatusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PetDto>> {
        const response = await this.petFindByStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for petFindByTagsGet without sending the request
     */
    async petFindByTagsGetRequestOpts(requestParameters: PetFindByTagsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pet/findByTags`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async petFindByTagsGetRaw(requestParameters: PetFindByTagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PetDto>>> {
        const requestOptions = await this.petFindByTagsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PetDtoFromJSON));
    }

    /**
     */
    async petFindByTagsGet(requestParameters: PetFindByTagsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PetDto>> {
        const response = await this.petFindByTagsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for petPetIdDelete without sending the request
     */
    async petPetIdDeleteRequestOpts(requestParameters: PetPetIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling petPetIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pet/{petId}`;
        urlPath = urlPath.replace('{petId}', encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async petPetIdDeleteRaw(requestParameters: PetPetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.petPetIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async petPetIdDelete(requestParameters: PetPetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.petPetIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for petPetIdGet without sending the request
     */
    async petPetIdGetRequestOpts(requestParameters: PetPetIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling petPetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pet/{petId}`;
        urlPath = urlPath.replace('{petId}', encodeURIComponent(String(requestParameters['petId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async petPetIdGetRaw(requestParameters: PetPetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetDto>> {
        const requestOptions = await this.petPetIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetDtoFromJSON(jsonValue));
    }

    /**
     */
    async petPetIdGet(requestParameters: PetPetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetDto> {
        const response = await this.petPetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for petPost without sending the request
     */
    async petPostRequestOpts(requestParameters: PetPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pet`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddPetRequestToJSON(requestParameters['addPetRequest']),
        };
    }

    /**
     */
    async petPostRaw(requestParameters: PetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetDto>> {
        const requestOptions = await this.petPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetDtoFromJSON(jsonValue));
    }

    /**
     */
    async petPost(requestParameters: PetPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetDto> {
        const response = await this.petPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for petPut without sending the request
     */
    async petPutRequestOpts(requestParameters: PetPutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pet`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePetRequestToJSON(requestParameters['updatePetRequest']),
        };
    }

    /**
     */
    async petPutRaw(requestParameters: PetPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetDto>> {
        const requestOptions = await this.petPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetDtoFromJSON(jsonValue));
    }

    /**
     */
    async petPut(requestParameters: PetPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetDto> {
        const response = await this.petPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
