/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OrderDto,
    OrderDtoFromJSON,
    OrderDtoToJSON,
} from '../models/OrderDto';
import {
    type PlaceOrderRequest,
    PlaceOrderRequestFromJSON,
    PlaceOrderRequestToJSON,
} from '../models/PlaceOrderRequest';

export interface StoreOrderOrderIdDeleteRequest {
    orderId: string;
}

export interface StoreOrderOrderIdGetRequest {
    orderId: string;
}

export interface StoreOrderPostRequest {
    placeOrderRequest?: PlaceOrderRequest;
}

/**
 * 
 */
export class StoreApi extends runtime.BaseAPI {

    /**
     * Creates request options for storeInventoryGet without sending the request
     */
    async storeInventoryGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/store/inventory`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async storeInventoryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: number; }>> {
        const requestOptions = await this.storeInventoryGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async storeInventoryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: number; }> {
        const response = await this.storeInventoryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storeOrderGet without sending the request
     */
    async storeOrderGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/store/order`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async storeOrderGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderDto>>> {
        const requestOptions = await this.storeOrderGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderDtoFromJSON));
    }

    /**
     */
    async storeOrderGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderDto>> {
        const response = await this.storeOrderGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storeOrderOrderIdDelete without sending the request
     */
    async storeOrderOrderIdDeleteRequestOpts(requestParameters: StoreOrderOrderIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling storeOrderOrderIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/store/order/{orderId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async storeOrderOrderIdDeleteRaw(requestParameters: StoreOrderOrderIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.storeOrderOrderIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async storeOrderOrderIdDelete(requestParameters: StoreOrderOrderIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.storeOrderOrderIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for storeOrderOrderIdGet without sending the request
     */
    async storeOrderOrderIdGetRequestOpts(requestParameters: StoreOrderOrderIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling storeOrderOrderIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/store/order/{orderId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async storeOrderOrderIdGetRaw(requestParameters: StoreOrderOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDto>> {
        const requestOptions = await this.storeOrderOrderIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDtoFromJSON(jsonValue));
    }

    /**
     */
    async storeOrderOrderIdGet(requestParameters: StoreOrderOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDto> {
        const response = await this.storeOrderOrderIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storeOrderPost without sending the request
     */
    async storeOrderPostRequestOpts(requestParameters: StoreOrderPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/store/order`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaceOrderRequestToJSON(requestParameters['placeOrderRequest']),
        };
    }

    /**
     */
    async storeOrderPostRaw(requestParameters: StoreOrderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDto>> {
        const requestOptions = await this.storeOrderPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDtoFromJSON(jsonValue));
    }

    /**
     */
    async storeOrderPost(requestParameters: StoreOrderPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDto> {
        const response = await this.storeOrderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
