/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddPetRequest
 */
export interface AddPetRequest {
    /**
     * 
     * @type {string}
     * @memberof AddPetRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPetRequest
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPetRequest
     */
    categoryId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddPetRequest
     */
    photoUrls?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddPetRequest
     */
    tagIds?: Array<string> | null;
}

/**
 * Check if a given object implements the AddPetRequest interface.
 */
export function instanceOfAddPetRequest(value: object): value is AddPetRequest {
    return true;
}

export function AddPetRequestFromJSON(json: any): AddPetRequest {
    return AddPetRequestFromJSONTyped(json, false);
}

export function AddPetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'photoUrls': json['photoUrls'] == null ? undefined : json['photoUrls'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
    };
}

export function AddPetRequestToJSON(json: any): AddPetRequest {
    return AddPetRequestToJSONTyped(json, false);
}

export function AddPetRequestToJSONTyped(value?: AddPetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
        'categoryId': value['categoryId'],
        'photoUrls': value['photoUrls'],
        'tagIds': value['tagIds'],
    };
}

