/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    petId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    quantity?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof OrderDto
     */
    shipDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    status?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDto
     */
    complete?: boolean;
}

/**
 * Check if a given object implements the OrderDto interface.
 */
export function instanceOfOrderDto(value: object): value is OrderDto {
    return true;
}

export function OrderDtoFromJSON(json: any): OrderDto {
    return OrderDtoFromJSONTyped(json, false);
}

export function OrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'petId': json['petId'] == null ? undefined : json['petId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'shipDate': json['shipDate'] == null ? undefined : (new Date(json['shipDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'complete': json['complete'] == null ? undefined : json['complete'],
    };
}

export function OrderDtoToJSON(json: any): OrderDto {
    return OrderDtoToJSONTyped(json, false);
}

export function OrderDtoToJSONTyped(value?: OrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'petId': value['petId'],
        'quantity': value['quantity'],
        'shipDate': value['shipDate'] == null ? value['shipDate'] : value['shipDate'].toISOString(),
        'status': value['status'],
        'complete': value['complete'],
    };
}

