/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryDto } from './CategoryDto';
import {
    CategoryDtoFromJSON,
    CategoryDtoFromJSONTyped,
    CategoryDtoToJSON,
    CategoryDtoToJSONTyped,
} from './CategoryDto';
import type { TagDto } from './TagDto';
import {
    TagDtoFromJSON,
    TagDtoFromJSONTyped,
    TagDtoToJSON,
    TagDtoToJSONTyped,
} from './TagDto';

/**
 * 
 * @export
 * @interface PetDto
 */
export interface PetDto {
    /**
     * 
     * @type {string}
     * @memberof PetDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PetDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PetDto
     */
    status?: string | null;
    /**
     * 
     * @type {CategoryDto}
     * @memberof PetDto
     */
    category?: CategoryDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof PetDto
     */
    photoUrls?: Array<string> | null;
    /**
     * 
     * @type {Array<TagDto>}
     * @memberof PetDto
     */
    tags?: Array<TagDto> | null;
}

/**
 * Check if a given object implements the PetDto interface.
 */
export function instanceOfPetDto(value: object): value is PetDto {
    return true;
}

export function PetDtoFromJSON(json: any): PetDto {
    return PetDtoFromJSONTyped(json, false);
}

export function PetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'category': json['category'] == null ? undefined : CategoryDtoFromJSON(json['category']),
        'photoUrls': json['photoUrls'] == null ? undefined : json['photoUrls'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagDtoFromJSON)),
    };
}

export function PetDtoToJSON(json: any): PetDto {
    return PetDtoToJSONTyped(json, false);
}

export function PetDtoToJSONTyped(value?: PetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'category': CategoryDtoToJSON(value['category']),
        'photoUrls': value['photoUrls'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagDtoToJSON)),
    };
}

