/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceOrderRequest
 */
export interface PlaceOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaceOrderRequest
     */
    petId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlaceOrderRequest
     */
    quantity?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PlaceOrderRequest
     */
    shipDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceOrderRequest
     */
    status?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlaceOrderRequest
     */
    complete?: boolean;
}

/**
 * Check if a given object implements the PlaceOrderRequest interface.
 */
export function instanceOfPlaceOrderRequest(value: object): value is PlaceOrderRequest {
    return true;
}

export function PlaceOrderRequestFromJSON(json: any): PlaceOrderRequest {
    return PlaceOrderRequestFromJSONTyped(json, false);
}

export function PlaceOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'petId': json['petId'] == null ? undefined : json['petId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'shipDate': json['shipDate'] == null ? undefined : (new Date(json['shipDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'complete': json['complete'] == null ? undefined : json['complete'],
    };
}

export function PlaceOrderRequestToJSON(json: any): PlaceOrderRequest {
    return PlaceOrderRequestToJSONTyped(json, false);
}

export function PlaceOrderRequestToJSONTyped(value?: PlaceOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'petId': value['petId'],
        'quantity': value['quantity'],
        'shipDate': value['shipDate'] == null ? value['shipDate'] : value['shipDate'].toISOString(),
        'status': value['status'],
        'complete': value['complete'],
    };
}

