/* tslint:disable */
/* eslint-disable */
/**
 * PetStore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePetRequest
 */
export interface UpdatePetRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePetRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePetRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePetRequest
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePetRequest
     */
    categoryId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePetRequest
     */
    photoUrls?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePetRequest
     */
    tagIds?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdatePetRequest interface.
 */
export function instanceOfUpdatePetRequest(value: object): value is UpdatePetRequest {
    return true;
}

export function UpdatePetRequestFromJSON(json: any): UpdatePetRequest {
    return UpdatePetRequestFromJSONTyped(json, false);
}

export function UpdatePetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'photoUrls': json['photoUrls'] == null ? undefined : json['photoUrls'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
    };
}

export function UpdatePetRequestToJSON(json: any): UpdatePetRequest {
    return UpdatePetRequestToJSONTyped(json, false);
}

export function UpdatePetRequestToJSONTyped(value?: UpdatePetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'categoryId': value['categoryId'],
        'photoUrls': value['photoUrls'],
        'tagIds': value['tagIds'],
    };
}

